


--CREAR USUARIO DE PROYECTO

CREATE USER DB_SPOTIFY
  IDENTIFIED BY "oracle"
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP;
ALTER USER DB_SPOTIFY QUOTA UNLIMITED ON USERS;

GRANT create session TO DB_SPOTIFY;
GRANT create table TO DB_SPOTIFY;
GRANT create view TO DB_SPOTIFY;
GRANT create any trigger TO DB_SPOTIFY;
GRANT create any procedure TO DB_SPOTIFY;
GRANT create sequence TO DB_SPOTIFY;
GRANT create synonym TO DB_SPOTIFY;
GRANT create materialized view TO DB_SPOTIFY;

